spring:
  jpa:
    show-sql: false
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    "[es.vargontoc]": ${LOGGING_LEVEL_ES_VARGONTOC:INFO}
    "[org.springframework.ai]": WARN
