server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc}
    username: ${SPRING_DATASOURCE_USERNAME:edu}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL}
      chat:
        model: ${SPRING_AI_OLLAMA_CHAT_MODEL:llama3.2}
      init:
        pull-model-strategy: never

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[es.vargontoc]": ${LOGGING_LEVEL_ES_VARGONTOC:INFO}
